export const environment = {
  articleApiBaseUrl: 'https://api.tenlastic.com/articles',
  connectionApiBaseUrl: 'https://api.tenlastic.com/connections',
  databaseApiBaseUrl: 'https://api.tenlastic.com/databases',
  friendApiBaseUrl: 'https://api.tenlastic.com/friends',
  gameApiBaseUrl: 'https://api.tenlastic.com/games',
  gameInvitationApiBaseUrl: 'https://api.tenlastic.com/game-invitations',
  gameServerApiBaseUrl: 'https://api.tenlastic.com/game-servers',
  groupApiBaseUrl: 'https://api.tenlastic.com/groups',
  groupInvitationApiBaseUrl: 'https://api.tenlastic.com/group-invitations',
  ignorationApiBaseUrl: 'https://api.tenlastic.com/ignorations',
  launcherUrl: 'https://minio.tenlastic.com/launcher/TenlasticLauncherSetup.exe',
  logApiBaseUrl: 'https://api.tenlastic.com/logs',
  loginApiBaseUrl: 'https://api.tenlastic.com/logins',
  messageApiBaseUrl: 'https://api.tenlastic.com/messages',
  namespaceApiBaseUrl: 'https://api.tenlastic.com/namespaces',
  passwordResetApiBaseUrl: 'https://api.tenlastic.com/password-resets',
  production: true,
  queueApiBaseUrl: 'https://api.tenlastic.com/queues',
  queueMemberApiBaseUrl: 'https://api.tenlastic.com/queue-members',
  refreshTokenApiBaseUrl: 'http://api.tenlastic.com/refresh-tokens',
  releaseApiBaseUrl: 'https://api.tenlastic.com/releases',
  useHash: true,
  userApiBaseUrl: 'https://api.tenlastic.com/users',
};
