export const environment = {
  articleApiBaseUrl: 'http://api.localhost/articles',
  connectionApiBaseUrl: 'http://api.localhost/connections',
  databaseApiBaseUrl: 'http://api.localhost/databases',
  friendApiBaseUrl: 'http://api.localhost/friends',
  gameApiBaseUrl: 'http://api.localhost/games',
  gameServerApiBaseUrl: 'http://api.localhost/game-servers',
  groupApiBaseUrl: 'http://api.localhost/groups',
  groupInvitationApiBaseUrl: 'http://api.localhost/group-invitations',
  ignorationApiBaseUrl: 'http://api.localhost/ignorations',
  launcherUrl: 'https://minio.tenlastic.com/launcher/TenlasticLauncherSetup.exe',
  loginApiBaseUrl: 'http://api.localhost/logins',
  messageApiBaseUrl: 'http://api.localhost/messages',
  namespaceApiBaseUrl: 'http://api.localhost/namespaces',
  passwordResetApiBaseUrl: 'http://api.localhost/password-resets',
  production: false,
  refreshTokenApiBaseUrl: 'http://api.localhost/refresh-tokens',
  releaseApiBaseUrl: 'http://api.localhost/releases',
  useHash: false,
  userApiBaseUrl: 'http://api.localhost/users',
};
