export const environment = {
  apiBaseUrl: 'http://wss.localhost',
  articleApiBaseUrl: 'http://api.localhost/articles',
  collectionApiBaseUrl: 'http://api.localhost/collections',
  friendApiBaseUrl: 'http://api.localhost/friends',
  gameApiBaseUrl: 'http://api.localhost/games',
  gameInvitationApiBaseUrl: 'http://api.localhost/game-invitations',
  gameServerApiBaseUrl: 'http://api.localhost/game-servers',
  groupApiBaseUrl: 'http://api.localhost/groups',
  groupInvitationApiBaseUrl: 'http://api.localhost/group-invitations',
  ignorationApiBaseUrl: 'http://api.localhost/ignorations',
  launcherUrl: 'https://minio.tenlastic.com/launcher/TenlasticLauncherSetup.exe',
  logApiBaseUrl: 'http://api.localhost/logs',
  loginApiBaseUrl: 'http://api.localhost/logins',
  matchApiBaseUrl: 'http://api.localhost/matches',
  messageApiBaseUrl: 'http://api.localhost/messages',
  namespaceApiBaseUrl: 'http://api.localhost/namespaces',
  passwordResetApiBaseUrl: 'http://api.localhost/password-resets',
  production: false,
  queueApiBaseUrl: 'http://api.localhost/queues',
  queueMemberApiBaseUrl: 'http://api.localhost/queue-members',
  refreshTokenApiBaseUrl: 'http://api.localhost/refresh-tokens',
  buildApiBaseUrl: 'http://api.localhost/builds',
  useHash: false,
  userApiBaseUrl: 'http://api.localhost/users',
  webSocketApiBaseUrl: 'http://api.localhost/web-sockets',
};
