export const environment = {
  articleApiBaseUrl: 'http://api.localhost/articles',
  connectionApiBaseUrl: 'http://api.localhost/connections',
  databaseApiBaseUrl: 'http://api.localhost/databases',
  friendApiBaseUrl: 'http://api.localhost/friends',
  gameApiBaseUrl: 'http://api.localhost/games',
  gameServerApiBaseUrl: 'http://api.localhost/game-servers',
  ignorationApiBaseUrl: 'http://api.localhost/ignorations',
  loginApiBaseUrl: 'http://api.localhost/logins',
  loginUrl: 'http://sso.localhost/login?redirectUrl=http://portal.localhost/oauth',
  logoutUrl: 'http://sso.localhost/logout?redirectUrl=http://portal.localhost/oauth',
  messageApiBaseUrl: 'http://api.localhost/messages',
  namespaceApiBaseUrl: 'http://api.localhost/namespaces',
  passwordResetApiBaseUrl: 'http://api.localhost/password-resets',
  production: true,
  refreshTokenApiBaseUrl: 'http://api.localhost/refresh-tokens',
  releaseApiBaseUrl: 'http://api.localhost/releases',
  userApiBaseUrl: 'http://api.localhost/users',
};
