export const environment = {
  articleApiBaseUrl: 'https://api.tenlastic.com/articles',
  connectionApiBaseUrl: 'https://api.tenlastic.com/connections',
  databaseApiBaseUrl: 'https://api.tenlastic.com/databases',
  friendApiBaseUrl: 'https://api.tenlastic.com/friends',
  gameApiBaseUrl: 'https://api.tenlastic.com/games',
  ignorationApiBaseUrl: 'https://api.tenlastic.com/ignorations',
  loginApiBaseUrl: 'https://api.tenlastic.com/logins',
  loginUrl: 'https://sso.tenlastic.com/login?redirectUrl=https://portal.tenlastic.com/oauth',
  logoutUrl: 'https://sso.tenlastic.com/logout?redirectUrl=https://portal.tenlastic.com/oauth',
  messageApiBaseUrl: 'https://api.tenlastic.com/messages',
  namespaceApiBaseUrl: 'https://api.tenlastic.com/namespaces',
  passwordResetApiBaseUrl: 'https://api.tenlastic.com/password-resets',
  production: true,
  releaseApiBaseUrl: 'https://api.tenlastic.com/releases',
  userApiBaseUrl: 'https://api.tenlastic.com/users',
};
