{
 "title": "MongoDB",
 "time": { "from": "2019-05-05T01:11:06.059Z", "to": "2019-05-05T13:11:06.059Z" },
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_connections{state=\"current\"}",
     "legendFormat": "{{pod_name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Query Operations (ops/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (type)(rate(mongodb_mongod_op_counters_total[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations (ops/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (state)(rate(mongodb_mongod_metrics_document_total[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}