{
 "title": "Velero",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Attempts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(velero_backup_attempt_total)"
    }
   ]
  },
  {
   "title": "Backup Attempts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "velero_backup_attempt_total", "legendFormat": "{{schedule}}" }
   ]
  },
  {
   "title": "Successful Backups",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "velero_backup_success_total", "legendFormat": "{{schedule}}" }
   ]
  },
  {
   "title": "Backup Successes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(velero_backup_success_total)"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "velero_backup_tarball_size_bytes",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "velero_backup_duration_seconds_sum",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "velero_backup_failure_total", "legendFormat": "{{schedule}}" }
   ]
  },
  {
   "title": "Backup Failures",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(velero_backup_failure_total)"
    }
   ]
  },
  { "title": "Volume Snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Volume Snapshot Attempts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(velero_volume_snapshot_attempt_total)"
    }
   ]
  },
  {
   "title": "Volume Snapshot Attempts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "velero_volume_snapshot_attempt_total",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Successful Volume Snapshots",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "velero_volume_snapshot_success_total",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Volume Snapshot Successes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(velero_volume_snapshot_success_total)"
    }
   ]
  },
  {
   "title": "Volume Shapshot Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "velero_volume_snapshot_failure_total",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Volume Snapshot Failures",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(velero_volume_snapshot_failure_total)"
    }
   ]
  },
  { "title": "Restores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Restore Attempts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(velero_restore_attempt_total)"
    }
   ]
  },
  {
   "title": "Restore Attempts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(velero_restore_attempt_total)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Restore Snapshots",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(velero_restore_success_total)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Restore Successes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(velero_restore_success_total)"
    }
   ]
  },
  {
   "title": "Restore Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(velero_restore_failed_total)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Restore Failures",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(velero_restore_failed_total)"
    }
   ]
  }
 ]
}