export const environment = {
  articleApiBaseUrl: 'http://localhost:3004/articles',
  databaseApiBaseUrl: 'http://localhost:3002/databases',
  friendApiBaseUrl: 'http://localhost:3006/friends',
  gameApiBaseUrl: 'http://localhost:3003/games',
  ignorationApiBaseUrl: 'http://localhost:3006/ignorations',
  launcherUrl: 'https://minio.tenlastic.com/launcher/TenlasticLauncherSetup.exe',
  loginApiBaseUrl: 'http://localhost:3000/logins',
  loginUrl: 'http://localhost:8082/login?redirectUrl=http://localhost:8083/oauth',
  logoutUrl: 'http://localhost:8082/logout?redirectUrl=http://localhost:8083/oauth',
  messageApiBaseUrl: 'http://localhost:3006/messages',
  namespaceApiBaseUrl: 'http://localhost:3001/namespaces',
  passwordResetApiBaseUrl: 'http://localhost:3000/password-resets',
  production: true,
  releaseApiBaseUrl: 'http://localhost:3005/releases',
  useHash: false,
  userApiBaseUrl: 'http://localhost:3000/users',
};
