export const environment = {
  articleApiBaseUrl: 'https://api.tenlastic.com/articles',
  databaseApiBaseUrl: 'https://api.tenlastic.com/databases',
  gameApiBaseUrl: 'https://api.tenlastic.com/games',
  launcherUrl: 'https://minio.tenlastic.com/launcher/TenlasticLauncherSetup.exe',
  loginApiBaseUrl: 'https://api.tenlastic.com/logins',
  loginUrl: 'https://sso.tenlastic.com/login?redirectUrl=https://launcher.tenlastic.com/oauth',
  logoutUrl: 'https://sso.tenlastic.com/logout?redirectUrl=https://launcher.tenlastic.com/oauth',
  namespaceApiBaseUrl: 'https://api.tenlastic.com/namespaces',
  passwordResetApiBaseUrl: 'https://api.tenlastic.com/password-resets',
  production: true,
  releaseApiBaseUrl: 'https://api.tenlastic.com/releases',
  useHash: false,
  userApiBaseUrl: 'https://api.tenlastic.com/users',
};
