export const environment = {
  articleApiBaseUrl: 'https://api.tenlastic.com/articles',
  databaseApiBaseUrl: 'https://api.tenlastic.com/databases',
  gameApiBaseUrl: 'https://api.tenlastic.com/games',
  launcherUrl: 'https://minio.tenlastic.com/launcher/TenlasticLauncherSetup.exe',
  loginApiBaseUrl: 'https://api.tenlastic.com/logins',
  loginUrl: 'https://sso.tenlastic.com/login',
  logoutUrl: 'https://sso.tenlastic.com/logout',
  namespaceApiBaseUrl: 'https://api.tenlastic.com/namespaces',
  passwordResetApiBaseUrl: 'https://api.tenlastic.com/password-resets',
  production: true,
  releaseApiBaseUrl: 'https://api.tenlastic.com/releases',
  useHash: true,
  userApiBaseUrl: 'https://api.tenlastic.com/users',
};
