export const environment = {
  articleApiBaseUrl: 'http://api.localhost/articles',
  connectionApiBaseUrl: 'http://api.localhost/connections',
  databaseApiBaseUrl: 'http://api.localhost/databases',
  friendApiBaseUrl: 'http://api.localhost/friends',
  gameApiBaseUrl: 'http://api.localhost/games',
  groupApiBaseUrl: 'http://api.localhost/groups',
  groupInvitationApiBaseUrl: 'http://api.localhost/group-invitations',
  ignorationApiBaseUrl: 'http://api.localhost/ignorations',
  launcherUrl: 'https://minio.tenlastic.com/launcher/TenlasticLauncherSetup.exe',
  loginApiBaseUrl: 'http://api.localhost/logins',
  loginUrl: 'http://sso.localhost/login?redirectUrl=http://platform.localhost/oauth',
  logoutUrl: 'http://sso.localhost/logout?redirectUrl=http://platform.localhost/oauth',
  messageApiBaseUrl: 'http://api.localhost/messages',
  namespaceApiBaseUrl: 'http://api.localhost/namespaces',
  passwordResetApiBaseUrl: 'http://api.localhost/password-resets',
  production: false,
  releaseApiBaseUrl: 'http://api.localhost/releases',
  useHash: false,
  userApiBaseUrl: 'http://api.localhost/users',
};
