import {
  Article,
  Authorization,
  Build,
  Collection,
  Friend,
  GameServer,
  Group,
  GroupInvitation,
  Ignoration,
  Message,
  Namespace,
  PasswordReset,
  Queue,
  QueueMember,
  RefreshToken,
  Storefront,
  User,
  WebSocket,
  Workflow,
} from './models';

export function deleteAll() {
  return Promise.all([
    Article.deleteMany({}),
    Authorization.deleteMany({}),
    Build.deleteMany({}),
    Collection.deleteMany({}),
    Friend.deleteMany({}),
    GameServer.deleteMany({}),
    Group.deleteMany({}),
    GroupInvitation.deleteMany({}),
    Ignoration.deleteMany({}),
    Message.deleteMany({}),
    Namespace.deleteMany({}),
    PasswordReset.deleteMany({}),
    Queue.deleteMany({}),
    QueueMember.deleteMany({}),
    RefreshToken.deleteMany({}),
    Storefront.deleteMany({}),
    User.deleteMany({}),
    WebSocket.deleteMany({}),
    Workflow.deleteMany({}),
  ]);
}
