import {
  Article,
  Authorization,
  Build,
  Collection,
  Friend,
  GameServer,
  Group,
  GroupInvitation,
  Ignoration,
  Message,
  Namespace,
  PasswordReset,
  Queue,
  QueueMember,
  RefreshToken,
  Storefront,
  User,
  WebSocket,
  Workflow,
} from './models';

export function syncIndexes() {
  return Promise.all([
    Article.syncIndexes({ background: true }),
    Authorization.syncIndexes({ background: true }),
    Build.syncIndexes({ background: true }),
    Collection.syncIndexes({ background: true }),
    Friend.syncIndexes({ background: true }),
    GameServer.syncIndexes({ background: true }),
    Group.syncIndexes({ background: true }),
    GroupInvitation.syncIndexes({ background: true }),
    Ignoration.syncIndexes({ background: true }),
    Message.syncIndexes({ background: true }),
    Namespace.syncIndexes({ background: true }),
    PasswordReset.syncIndexes({ background: true }),
    Queue.syncIndexes({ background: true }),
    QueueMember.syncIndexes({ background: true }),
    RefreshToken.syncIndexes({ background: true }),
    Storefront.syncIndexes({ background: true }),
    User.syncIndexes({ background: true }),
    WebSocket.syncIndexes({ background: true }),
    Workflow.syncIndexes({ background: true }),
  ]);
}
