#!/usr/bin/env bash
set -e

# Initiaize istio-system namespace.
kubectl create namespace istio-system

# Initialize Kiali secret for login.
kubectl apply -f ./kubernetes/kiali/secret.yml

# Change to the Istio directory.
cd ./istio/

# Initialize Istio.
helm install install/kubernetes/helm/istio-init \
  --name "istio-init" \
  --namespace "istio-system"

# Wait for install to finish.
echo "Waiting for install to finish..."
sleep 30

# Install Istio.
helm install install/kubernetes/helm/istio \
  -f "../helm/values/istio.yml" \
  --name "istio" \
  --namespace "istio-system"

# Enable Sidecar injection.
kubectl label namespace default istio-injection=enabled \
  --overwrite

# Redirect from HTTP to HTTPS.
kubectl -n istio-system patch gateway istio-autogenerated-k8s-ingress \
  --type "json" \
  -p '[{"op": "replace", "path": "/spec/servers/0/tls", "value": {"httpsRedirect": true}}]'

# Load SSL certificate for HTTPS requests.
kubectl -n istio-system patch gateway istio-autogenerated-k8s-ingress \
  --type "json" \
  -p '[{"op": "replace", "path": "/spec/servers/1/tls", "value": {"mode": "SIMPLE","privateKey":"/etc/istio/ingressgateway-certs/tls.key","serverCertificate":"/etc/istio/ingressgateway-certs/tls.crt"}}]'
