import {
  Article,
  Build,
  BuildLog,
  Collection,
  Friend,
  Game,
  GameInvitation,
  GameServer,
  GameServerLog,
  Group,
  GroupInvitation,
  Ignoration,
  Message,
  Namespace,
  PasswordReset,
  Queue,
  QueueLog,
  QueueMember,
  RefreshToken,
  User,
  WebSocket,
  Workflow,
  WorkflowLog,
} from './models';

export function deleteAll() {
  return Promise.all([
    Article.deleteMany({}),
    Build.deleteMany({}),
    BuildLog.deleteMany({}),
    Collection.deleteMany({}),
    Friend.deleteMany({}),
    Game.deleteMany({}),
    GameInvitation.deleteMany({}),
    GameServer.deleteMany({}),
    GameServerLog.deleteMany({}),
    Group.deleteMany({}),
    GroupInvitation.deleteMany({}),
    Ignoration.deleteMany({}),
    Message.deleteMany({}),
    Namespace.deleteMany({}),
    PasswordReset.deleteMany({}),
    Queue.deleteMany({}),
    QueueLog.deleteMany({}),
    QueueMember.deleteMany({}),
    RefreshToken.deleteMany({}),
    User.deleteMany({}),
    WebSocket.deleteMany({}),
    Workflow.deleteMany({}),
    WorkflowLog.deleteMany({}),
  ]);
}
