import {
  Article,
  Collection,
  File,
  Friend,
  Game,
  GameInvitation,
  GameServer,
  Group,
  GroupInvitation,
  Ignoration,
  Log,
  Message,
  Namespace,
  PasswordReset,
  Queue,
  QueueMember,
  RefreshToken,
  Release,
  ReleaseTask,
  User,
  WebSocket,
} from './models';

export function deleteAll() {
  return Promise.all([
    Article.deleteMany({}),
    Collection.deleteMany({}),
    File.deleteMany({}),
    Friend.deleteMany({}),
    Game.deleteMany({}),
    GameInvitation.deleteMany({}),
    GameServer.deleteMany({}),
    Group.deleteMany({}),
    GroupInvitation.deleteMany({}),
    Ignoration.deleteMany({}),
    Log.deleteMany({}),
    Message.deleteMany({}),
    Namespace.deleteMany({}),
    PasswordReset.deleteMany({}),
    Queue.deleteMany({}),
    QueueMember.deleteMany({}),
    RefreshToken.deleteMany({}),
    Release.deleteMany({}),
    ReleaseTask.deleteMany({}),
    User.deleteMany({}),
    WebSocket.deleteMany({}),
  ]);
}
