import {
  Article,
  Build,
  BuildLog,
  Collection,
  Friend,
  Game,
  GameInvitation,
  GameServer,
  GameServerLog,
  Group,
  GroupInvitation,
  Ignoration,
  Message,
  Namespace,
  PasswordReset,
  Queue,
  QueueLog,
  QueueMember,
  RefreshToken,
  User,
  WebSocket,
  Workflow,
  WorkflowLog,
} from './models';

export function syncIndexes() {
  return Promise.all([
    Article.syncIndexes({ background: true }),
    Build.syncIndexes({ background: true }),
    BuildLog.syncIndexes({ background: true }),
    Collection.syncIndexes({ background: true }),
    Friend.syncIndexes({ background: true }),
    Game.syncIndexes({ background: true }),
    GameInvitation.syncIndexes({ background: true }),
    GameServer.syncIndexes({ background: true }),
    GameServerLog.syncIndexes({ background: true }),
    Group.syncIndexes({ background: true }),
    GroupInvitation.syncIndexes({ background: true }),
    Ignoration.syncIndexes({ background: true }),
    Message.syncIndexes({ background: true }),
    Namespace.syncIndexes({ background: true }),
    PasswordReset.syncIndexes({ background: true }),
    Queue.syncIndexes({ background: true }),
    QueueLog.syncIndexes({ background: true }),
    QueueMember.syncIndexes({ background: true }),
    RefreshToken.syncIndexes({ background: true }),
    User.syncIndexes({ background: true }),
    WebSocket.syncIndexes({ background: true }),
    Workflow.syncIndexes({ background: true }),
    WorkflowLog.syncIndexes({ background: true }),
  ]);
}
